server:
  port: 8080
spring:
  application:
    name: "JavaReactiveTest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    timeout: 5000
    url: "https://run.mocky.io"
